
group 'com.yandex.pay.flutter_plugin'
version '1.0-SNAPSHOT'


buildscript {
    ext.kotlin_version = '2.0.20'
    repositories {
        google()
        mavenCentral()
        // при желании можно удалить r8 — AGP 8.x содержит R8
        maven { url = uri("https://storage.googleapis.com/r8-releases/raw") }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.7.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:${kotlin_version}"
        // classpath 'com.android.tools:r8:8.2.24' // обычно не нужен
    }
}

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

// Flutter tooling must be applied after Android & Kotlin plugins
// so that the `android {}` extension already exists


def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}


android {
    namespace 'com.yandex.pay.ypay_android'
    compileSdk 34

    defaultConfig {
        minSdkVersion 24
        targetSdkVersion 34

        manifestPlaceholders = [
                YANDEX_CLIENT_ID: (project.findProperty("YANDEX_CLIENT_ID") ?: "")
        ]
        consumerProguardFiles 'consumer-rules.pro'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
        test.java.srcDirs += 'src/test/kotlin'
    }
}

// ВАЖНО: здесь только зависимости, без repositories{}
dependencies {
    implementation 'com.yandex.pay:pay:2.5.0'
    implementation 'androidx.browser:browser:1.8.0'

    testImplementation "org.jetbrains.kotlin:kotlin-test:${kotlin_version}"
    testImplementation 'org.mockito:mockito-core:5.0.0'
}