group 'com.yandex.pay.flutter_plugin'
version '1.0-SNAPSHOT'

buildscript {
    ext.kotlin_version = '2.0.20'
    repositories {
        google()
        mavenCentral()
        maven { url = uri("https://storage.googleapis.com/r8-releases/raw") }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.7.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:${kotlin_version}"
    }
}

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    namespace 'com.yandex.pay.ypay_android'
    compileSdk 34

    defaultConfig {
        minSdkVersion 24
        targetSdkVersion 34
        manifestPlaceholders = [ YANDEX_CLIENT_ID: (project.findProperty("YANDEX_CLIENT_ID") ?: "") ]
        consumerProguardFiles 'consumer-rules.pro'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
        test.java.srcDirs += 'src/test/kotlin'
    }
}

dependencies {
    implementation 'com.yandex.pay:pay:2.5.0'
    implementation 'androidx.browser:browser:1.8.0'

    testImplementation "org.jetbrains.kotlin:kotlin-test:${kotlin_version}"
    testImplementation 'org.mockito:mockito-core:5.0.0'
}